eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8990
spring:
  application:
    name: zipkin-client1
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411